version: '3.9'
services:
  db:
    image: postgres
    container_name: pg_for_django
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: budget
    volumes:
      - c:\users\filim\documents\goit\hw13\pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
