# Generated by Django 3.2.7 on 2021-09-30 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.IntegerField(choices=[(1, 'Debit'), (-1, 'Credit')], help_text='Choose from enumerate list the type of transaction for help us to prepare the valid classifier')),
                ('record_class', models.CharField(help_text='Should be unique for each debit or credit operation type', max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Owner of classes')),
            ],
        ),
        migrations.CreateModel(
            name='GrossBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.datetime(2021, 9, 30, 9, 57, 42, 291020, tzinfo=utc), help_text='If date does not set - current date would be used ')),
                ('record_type', models.IntegerField(choices=[(1, 'Debit'), (-1, 'Credit')], help_text='Choose from enumerate list the type of transaction for help us to prepare the valid classifier')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Please use ONE currency for all your records', max_digits=10)),
                ('record_class', models.ForeignKey(help_text='Record class you could choose from the list. If you doesnt find suitable class, please create one', on_delete=django.db.models.deletion.CASCADE, to='budget_review.transactionclassifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL, verbose_name='Owner of budget')),
            ],
        ),
    ]
